(() => {
const U=window.TECHMATE_SUPABASE_URL,K=window.TECHMATE_SUPABASE_KEY,H={apikey:K,Authorization:`Bearer ${K}`,'Content-Type':'application/json'};const EDIT=document.body.dataset.editable==='true',grid=document.getElementById('leaderGrid');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function api(path,opt={}){const r=await fetch(U+'/rest/v1/'+path,{...opt,headers:{...H,...(opt.headers||{})}});const t=await r.text();if(!r.ok)throw Error(t);return t?JSON.parse(t):[]}
async function get(){return api('techmate_club_leaders?select=*&order=name.asc')}
function render(rows){grid.innerHTML=rows.length?rows.map(p=>`<article class="club-card">${p.photo?`<img class="club-photo" src="${p.photo}" alt="${esc(p.name)}">`:`<div class="club-placeholder">${esc((p.name||'?')[0].toUpperCase())}</div>`}<h3>${esc(p.name)}</h3><p>${esc(p.role||'Club Leader')}</p>${EDIT?`<div class="card-actions"><button class="small-btn edit-leader" data-id="${p.id}">Edit</button><button class="small-btn delete-leader" data-id="${p.id}">Delete</button></div>`:''}</article>`).join(''):'<div class="empty">No club leaders yet.</div>';if(EDIT)bind(rows)}
async function load(){try{render(await get())}catch(e){grid.innerHTML=`<div class="empty">${esc(e.message)}<br><br>Run the latest SETUP_SQL.sql in Supabase.</div>`}}
function resizeImage(file){return new Promise((resolve,reject)=>{const rd=new FileReader();rd.onload=()=>{const img=new Image();img.onload=()=>{const max=500,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.82))};img.onerror=reject;img.src=rd.result};rd.onerror=reject;rd.readAsDataURL(file)})}
function bind(rows){document.querySelectorAll('.edit-leader').forEach(b=>b.onclick=()=>{const x=rows.find(v=>String(v.id)===b.dataset.id);leaderId.value=x.id;leaderName.value=x.name;leaderRole.value=x.role||'Club Leader';window._oldLeaderPhoto=x.photo||'';leaderPreview.src=x.photo||'';leaderPreview.hidden=!x.photo;leaderStatus.textContent='Editing '+x.name;document.getElementById('leaderForm').scrollIntoView({behavior:'smooth',block:'center'})});document.querySelectorAll('.delete-leader').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this club leader?'))return;try{await api(`techmate_club_leaders?id=eq.${b.dataset.id}`,{method:'DELETE'});await load()}catch(e){alert(e.message)}})}
if(EDIT){const form=document.getElementById('leaderForm'),file=document.getElementById('leaderPhoto'),preview=document.getElementById('leaderPreview'),status=document.getElementById('leaderStatus');file.onchange=async()=>{if(file.files[0]){preview.src=await resizeImage(file.files[0]);preview.hidden=false}};document.getElementById('removeLeaderPhoto').onclick=()=>{preview.src='';preview.hidden=true;file.value='';window._removeLeaderPhoto=true};document.getElementById('cancelLeader').onclick=()=>{form.reset();leaderId.value='';preview.hidden=true;status.textContent='';window._oldLeaderPhoto='';window._removeLeaderPhoto=false};form.onsubmit=async e=>{e.preventDefault();const id=leaderId.value,name=leaderName.value.trim(),role=leaderRole.value.trim()||'Club Leader';if(!name){status.textContent='Enter a name.';return}status.textContent='Saving...';try{let photo=window._removeLeaderPhoto?'':window._oldLeaderPhoto||'';if(file.files[0])photo=await resizeImage(file.files[0]);const data={name,role,photo};if(id)await api(`techmate_club_leaders?id=eq.${id}`,{method:'PATCH',body:JSON.stringify(data)});else await api('techmate_club_leaders',{method:'POST',body:JSON.stringify(data)});status.textContent='Saved!';form.reset();leaderId.value='';preview.hidden=true;window._oldLeaderPhoto='';window._removeLeaderPhoto=false;await load()}catch(e){status.textContent=e.message}}}
load();setInterval(load,3000);
})();